FROM maven:3.8.7-openjdk-18-slim as build
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN mvn package

FROM eclipse-temurin:17-jdk
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/target/helloworld.jar app.jar
CMD ["java", "-jar", "app.jar"]
