# Use a imagem oficial do OpenJDK
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo .jar gerado do seu diretório de build para o contêiner
COPY out/artifacts/house_of_books/house_of_books.jar /app/house_of_books.jar

# Exponha a porta 8084 (o novo número da porta)
EXPOSE 8084

# Defina o comando para rodar o JAR da sua aplicação
CMD ["java", "-jar", "house_of_books.jar"]
