# Etapa 1: Build
FROM maven:3.8.7-openjdk-17 AS builder

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia o código fonte para o container
COPY . .

# Compila o projeto e gera o JAR
RUN mvn clean package -DskipTests

# Etapa 2: Runtime
FROM openjdk:17-jdk-slim

# Diretório de trabalho para o runtime
WORKDIR /app

# Copia o JAR gerado na etapa de build para o contêiner
COPY --from=builder /app/target/house-of-books-0.0.1-SNAPSHOT.jar app.jar

# Porta que a aplicação usará
EXPOSE 8080

# Comando para executar o JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
