spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        envers:
          audit_table_suffix: _AUD
          store_date_at_delete: true