spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        envers:
          audit_table_suffix: _AUD
          store_date_at_delete: true