name: CI for Java Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Adicionar permissão de execução ao mvnw
      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      # Instalar dependências e compilar
      - name: Install dependencies and build
        run: ./mvnw clean install

      # Executar testes
      - name: Run tests
        run: ./mvnw test

      # Empacotar o projeto (Se for necessário gerar um JAR ou WAR)
      - name: Package project
        run: ./mvnw package -DskipTests

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t myusername/myapp:latest .
      
      # Fazer login no Docker Hub (ou outro registry, como AWS ECR)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push da imagem Docker para o Docker Hub (ou outro registry)
      - name: Push Docker image
        run: |
          docker push myusername/myapp:latest
      
      # Deploy no Render ou outro serviço (exemplo com API do Render)
      - name: Deploy to Render
        run: |
          curl -sSL https://render.com/deploy?image=myusername/myapp:latest \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
