name: CI for Java Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Instalar dependências e compilar
      - name: Install dependencies and build
        run: ./mvnw clean install

      # Executar testes
      - name: Run tests
        run: ./mvnw test
